package com.lightningkite.lightningserver.sessions.proofs

import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import kotlin.io.encoding.Base64


private const val prefix = "PBKDF2WithHmacSHA512."


/**
 * Securely hashes a string in a way that could be used for password storage.
 */
public fun String.secureHash(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""
    val salt = ByteArray(16)
    SecureRandom().nextBytes(salt)
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100000, 512)
    val key = skf.generateSecret(spec)
    Base64.encode(salt)
    return prefix + Base64.encode(salt) + "." + Base64.encode(key.encoded)
}

/**
 * Checks hashes generated by [secureHash].
 */
public fun String.checkAgainstHash(againstHash: String): Boolean {
    if (againstHash.isEmpty()) return false
    val against = againstHash.removePrefix(prefix)
    val salt = Base64.decode(against.substringBefore('.'))
    val rest = against.substringAfter('.')
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100000, 512)
    val key = skf.generateSecret(spec)
    return Base64.encode(key.encoded) == rest
}
