package com.lightningkite.lightningserver.typed

import com.lightningkite.lightningdb.*
import com.lightningkite.serialization.*
import com.lightningkite.lightningserver.core.ServerPath
import com.lightningkite.lightningserver.http.HttpMethod
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.*
import kotlin.reflect.KClass
import kotlin.reflect.KType

fun Documentable.Companion.typescriptSdk(out: Appendable) = with(out) {
    val safeDocumentables =
        endpoints.filter { it.inputType == Unit.serializer() || it.route.method != HttpMethod.GET }.toList()
    appendLine("import { ${fromLightningServerPackage.joinToString()}, apiCall, Path } from '@lightningkite/lightning-server-simplified'")
    appendLine()

    usedTypes
        .filter { it.descriptor.simpleSerialName !in skipFromLsPackage }
        .sortedBy { it.descriptor.simpleSerialName }
        .distinctBy { it.write() }
        .forEach {
            when (it.descriptor.kind) {
                is StructureKind.CLASS -> {
                    if (it is MySealedClassSerializer) return@forEach

                    val genericMap: Map<String, String> = it.getGenerics()
                        ?.withIndex()
                        ?.associate { (index, value) ->
                            value.write() to "T${if (index > 0) index else ""}"
                        } ?: emptyMap()


                    fun String.replaceGenerics(): String =
                        genericMap.entries.fold(this) { acc, (old, new) -> acc.replace(old, new) }

                    appendLine("export interface ${it.write().replaceGenerics()} {")
                    (it.serializableProperties?.map { it.serializer } ?: it.tryChildSerializers()?.toList()
                    ?: listOf()).forEachIndexed { index, sub ->
                        appendLine("    ${it.descriptor.getElementName(index)}: ${sub.write().replaceGenerics()}")
                    }
                    appendLine("}")
                }

                is SerialKind.ENUM -> {
                    append("export enum ")
                    it.write().let { out.append(it) }
                    appendLine(" {")
                    for (index in 0 until it.descriptor.elementsCount) {
                        append("    ")
                        it.descriptor.getElementName(index).first()
                            .let { if (it.isJavaIdentifierStart()) it else '_' }.let { append(it) }
                        it.descriptor.getElementName(index).drop(1)
                            .map { if (it.isJavaIdentifierPart()) it else '_' }.forEach { append(it) }
                        append(" = \"")
                        append(it.descriptor.getElementName(index))
                        append("\",")
                        appendLine()
                    }
                    appendLine("}")
                }

                is PrimitiveKind.STRING -> {
                    if (it.descriptor.simpleSerialName != "String") {
                        appendLine(
                            "export type ${it.descriptor.simpleSerialName} = string  // ${it.descriptor.serialName}".replace(
                                "/loose",
                                ""
                            )
                        )
                    }
                }

                else -> {}
            }
            appendLine()
        }

    appendLine()
    appendLine()


    val byGroup = safeDocumentables.groupBy { it.docGroupIdentifier }
    val groups = byGroup.keys.filterNotNull().sortedBy { it.groupToPartName() }
    appendLine("export interface Api {")
    for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
        append("    ")
        append(entry.functionName)
        this.functionHeader(entry)
        appendLine()
    }
    appendLine()
    for (group in groups) {
        val groupEndpoints = byGroup[group] ?: continue

        if (groupEndpoints.hasAutoEndpoints()) {
            val autoGeneratedInterface =
                groupEndpoints.firstOrNull { it.functionName == "detail" }?.outputType?.write()
            append("    readonly ${group.groupToPartName()}: ApiRestEndpoint<${autoGeneratedInterface}>")

            val nonAutogeneratedEndpoints = groupEndpoints.nonAutoGenerated()
            if (nonAutogeneratedEndpoints.isNotEmpty()) {
                appendLine(" & {")
                for (entry in nonAutogeneratedEndpoints) {
                    append("        ")
                    append(entry.functionName)
                    this.functionHeader(entry)
                    appendLine()
                }
                appendLine("    }")
            } else {
                appendLine()
            }
        } else {
            appendLine("    readonly ${group.groupToPartName()}: {")
            for (entry in groupEndpoints) {
                append("        ")
                append(entry.functionName)
                this.functionHeader(entry)
                appendLine()
            }
            appendLine("    }")
        }
    }
    appendLine("}")

    appendLine()
    appendLine()
    appendLine()

    val byUserType = safeDocumentables.groupBy { it.primaryAuthName }
    val userTypes = byUserType.keys.filterNotNull()
    userTypes.forEach { userType ->
        @Suppress("NAME_SHADOWING") val byGroup =
            ((byUserType[userType] ?: listOf()) + (byUserType[null] ?: listOf())).groupBy { it.docGroupIdentifier }
        @Suppress("NAME_SHADOWING") val groups = byGroup.keys.filterNotNull().sortedBy { it.groupToPartName() }

        val sessionClassName = "${userType.substringAfterLast('.')}Session"
        appendLine("export class $sessionClassName {")
        appendLine("    constructor(public api: Api, public ${userType.userTypeTokenName()}: () => string) {}")
        for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
            appendLine("    ")
            append("    ")
            append(entry.functionName)
            this.functionHeader(entry, skipAuth = true)
            append(" { return this.api.")
            functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
            appendLine(" } ")
        }

        appendLine(
            """
    private generateAutoEndpoints = <T extends {_id: string}, E extends ApiRestEndpoint<T> = any>(endpoint: E): SessionRestEndpoint<T> => ({
        default: () => endpoint.default(this.${userType.userTypeTokenName()}()),
        query: (input) => endpoint.query(input, this.${userType.userTypeTokenName()}()),
        queryPartial: (input) => endpoint.queryPartial(input, this.${userType.userTypeTokenName()}()) as any,
        detail: (id) => endpoint.detail(id, this.${userType.userTypeTokenName()}()),
        insertBulk: (input) => endpoint.insertBulk(input, this.${userType.userTypeTokenName()}()),
        insert: (input) => endpoint.insert(input, this.${userType.userTypeTokenName()}()),
        upsert: (id, input) => endpoint.upsert(id, input, this.${userType.userTypeTokenName()}()),
        bulkReplace: (input) => endpoint.bulkReplace(input, this.${userType.userTypeTokenName()}()),
        replace: (id, input) => endpoint.replace(id, input, this.${userType.userTypeTokenName()}()),
        bulkModify: (input) => endpoint.bulkModify(input, this.${userType.userTypeTokenName()}()),
        modifyWithDiff: (id, input) => endpoint.modifyWithDiff(id, input, this.${userType.userTypeTokenName()}()),
        modify: (id, input) => endpoint.modify(id, input, this.${userType.userTypeTokenName()}()),
        simplifiedModify: (id, input) => endpoint.simplifiedModify(id, input, this.${userType.userTypeTokenName()}()),
        bulkDelete: (input) => endpoint.bulkDelete(input, this.${userType.userTypeTokenName()}()),
        delete: (id) => endpoint.delete(id, this.${userType.userTypeTokenName()}()),
        count: (input) => endpoint.count(input, this.${userType.userTypeTokenName()}()),
        groupCount: (input) => endpoint.groupCount(input, this.${userType.userTypeTokenName()}()),
        aggregate: (input) => endpoint.aggregate(input, this.${userType.userTypeTokenName()}()),
        groupAggregate: (input) => endpoint.groupAggregate(input, this.${userType.userTypeTokenName()}()),
    })
        """
        )
        appendLine()

        for (group in groups) {
            val groupEndpoints = byGroup[group] ?: continue
            if (groupEndpoints.hasAutoEndpoints()) {
                val autoGeneratedInterface =
                    groupEndpoints.firstOrNull { it.functionName == "detail" }?.outputType?.write()
                appendLine("    readonly ${group.groupToPartName()} = {")
                append("        ")
                appendLine("...this.generateAutoEndpoints<${autoGeneratedInterface}>(this.api.${group.groupToPartName()}),")
                for (entry in groupEndpoints.nonAutoGenerated()) {
                    append("        ")
                    append(entry.functionName)
                    append(": ")
                    this.functionHeader(entry, skipAuth = true)
                    append(" => { return this.api.")
                    append(group.groupToPartName())
                    append(".")
                    functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
                    appendLine(" }, ")
                }
                appendLine("    }")
            } else {
                appendLine("    readonly ${group.groupToPartName()} = {")
                for (entry in groupEndpoints) {
                    append("        ")
                    append(entry.functionName)
                    append(": ")
                    this.functionHeader(entry, skipAuth = true)
                    append(" => { return this.api.")
                    append(group.groupToPartName())
                    append(".")
                    functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
                    appendLine(" }, ")
                }
                appendLine("    }")
            }


        }
        appendLine("}")
        appendLine()
    }

    appendLine()
    appendLine()
    appendLine()


    appendLine("export class LiveApi implements Api {")
    appendLine("    public constructor(public httpUrl: string, public socketUrl: string = httpUrl, public extraHeaders: Record<string, string> = {}, public responseInterceptors?: (x: Response)=>Response) {}")

    appendLine(
        """
    private makeApiCall = <T, R>(
        subPath: string,
        method: string,
        input: T | undefined,
        userToken: string | undefined
    ): Promise<R> => {
        return apiCall<T>(
            `${"$"}{this.httpUrl}${"$"}{subPath}`,
            input as T,
            {
                method,
                headers: userToken
                    ? { ...this.extraHeaders, Authorization: `Bearer ${"$"}{userToken}` }
                    : this.extraHeaders,
            },
            undefined,
            this.responseInterceptors
        ).then((x) => x.json());
    };

    private generateCommonEndpoints = <T extends {_id: string}>(path: string): ApiRestEndpoint<T>  => ({
        default: (userToken) => this.makeApiCall(`${"$"}{path}/_default_`, "GET", undefined, userToken),
        query: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/query`, "POST", input, userToken),
        queryPartial: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/query-partial`, "POST", input, userToken) as any,
        detail: (id, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}`, "GET", undefined, userToken),
        insertBulk: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/bulk`, "POST", input, userToken),
        insert: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest`, "POST", input, userToken),
        upsert: (id, input, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}`, "POST", input, userToken),
        bulkReplace: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest`, "PUT", input, userToken),
        replace: (id, input, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}`, "PUT", input, userToken),
        bulkModify: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/bulk`, "PATCH", input, userToken),
        modifyWithDiff: (id, input, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}/delta`, "PATCH", input, userToken),
        modify: (id, input, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}`, "PATCH", input, userToken),
        simplifiedModify: (id, input, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}/simplified`, "PATCH", input, userToken),
        bulkDelete: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/bulk-delete`, "POST", input, userToken),
        delete: (id, userToken) => this.makeApiCall(`${"$"}{path}/rest/${"$"}{id}`, "DELETE", undefined, userToken),
        count: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/count`, "POST", input, userToken),
        groupCount: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/group-count`, "POST", input, userToken),
        aggregate: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/aggregate`, "POST", input, userToken),
        groupAggregate: (input, userToken) => this.makeApiCall(`${"$"}{path}/rest/group-aggregate`, "POST", input, userToken),
    });
    """
    )
    appendLine()
    appendLine()

    for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
        append("    ")
        append(entry.functionName)
        this.functionHeader(entry, skipAuth = false)
        appendLine(" {")
        val hasInput = entry.inputType != Unit.serializer()
        append("        return this.makeApiCall<${entry.inputType.write()}, ${entry.outputType.write()}>(")
        append(
            listOf(
                "`${entry.path.path.escaped}`",
                "\"${entry.route.method}\"",
                if (hasInput) "input" else "undefined",
                entry.primaryAuthName?.userTypeTokenName() ?: "undefined"
            ).joinToString(", ")
        )
        appendLine(")")
        appendLine("    }")
    }




    for (group in groups.sortedBy { it.groupToPartName() }) {
        val groupEndpoints = byGroup[group] ?: continue
        appendLine("    readonly ${group.groupToPartName()}: Api[\"${group.groupToPartName()}\"] = {")

        val explicitEndpoints =
            if (groupEndpoints.hasAutoEndpoints()) groupEndpoints.nonAutoGenerated() else groupEndpoints

        if (groupEndpoints.hasAutoEndpoints()) {
            val autoGeneratedInterface =
                byGroup[group]!!.firstOrNull { it.functionName == "detail" }?.outputType?.write()
            append("        ")
            appendLine(
                "...this.generateCommonEndpoints(\"${
                    groupEndpoints.first().path.path.escaped.split("/rest").first()
                }\"),"
            )
        }

        for (entry in explicitEndpoints) {
            append("        ")
            append(entry.functionName)
            append(": ")
            this.functionHeader(entry, skipAuth = false, skipTsTypes = true)
            val hasInput = entry.inputType != Unit.serializer()
            append(" => this.makeApiCall(")
            append(
                listOf(
                    "`${entry.path.path.escaped}`",
                    "\"${entry.route.method}\"",
                    if (hasInput) "input" else "undefined",
                    entry.primaryAuthName?.userTypeTokenName() ?: "undefined"
                ).joinToString(", ")
            )
            appendLine("),")
        }
        appendLine("    }")
    }
    appendLine("}")
    appendLine()
}


private val fromLightningServerPackage = setOf(
    "Query",
    "MassModification",
    "EntryChange",
    "ListChange",
    "Modification",
    "Condition",
    "GroupCountQuery",
    "AggregateQuery",
    "GroupAggregateQuery",
    "Aggregate",
    "SortPart",
    "DataClassPath",
    "DataClassPathPartial",
    "QueryPartial",
    "DeepPartial",
    "SessionRestEndpoint",
    "ApiRestEndpoint"
)
private val skipFromLsPackage = setOf(
    "Partial",
) + fromLightningServerPackage

private fun String.groupToPartName(): String = replaceFirstChar { it.lowercase() }

@Suppress("UNCHECKED_CAST")
private fun KType?.userTypeTokenName(): String = (this?.classifier as? KClass<Any>)?.userTypeTokenName() ?: "token"
private fun KClass<*>.userTypeTokenName(): String =
    simpleName?.replaceFirstChar { it.lowercase() }?.plus("Token") ?: "token"

private fun Appendable.functionHeader(
    documentable: Documentable,
    skipAuth: Boolean = false,
    overrideUserType: String? = null,
    skipTsTypes: Boolean = false
) {
    append("(")
    var argComma = false
    arguments(documentable, skipAuth, overrideUserType).forEach {
        if (argComma) append(", ")
        else argComma = true
        append(it.name)
        if (!skipTsTypes) {
            if (it.optional) append("?")
            append(": ")
            it.type?.write()?.let { append(it) } ?: it.stringType?.let { append(it) }
        }
    }
    if (skipTsTypes) {
        append(")")
    } else {
        append("): ")
        when (documentable) {
            is ApiEndpoint<*, *, *, *> -> {
                append("Promise<")
                documentable.outputType.write().let { append(it) }
                append(">")
            }

            is ApiWebsocket<*, *, *, *, *> -> {
                append("Observable<WebSocketIsh<")
                documentable.inputType.write().let { append(it) }
                append(", ")
                documentable.outputType.write().let { append(it) }
                append(">>")
            }

            else -> TODO()
        }
    }
}

private fun Appendable.functionCall(
    documentable: Documentable,
    skipAuth: Boolean = false,
    authUsesThis: Boolean = false,
    overrideUserType: String? = null
) {
    append("${documentable.functionName}(")
    var argComma = false
    arguments(documentable, skipAuth, overrideUserType).forEach {
        if (argComma) append(", ")
        else argComma = true
        if (it.name == documentable.primaryAuthName?.userTypeTokenName() && authUsesThis) {
            append("this.${it.name}()")
        } else {
            append(it.name)
        }
    }
    append(")")
}

private data class TArg(
    val name: String,
    val type: KSerializer<*>? = null,
    val stringType: String? = null,
    val default: String? = null,
    val optional: Boolean = false
)

private fun arguments(
    documentable: Documentable,
    skipAuth: Boolean = false,
    overrideUserType: String? = null
): List<TArg> = when (documentable) {
    is ApiEndpoint<*, *, *, *> -> listOfNotNull(
        documentable.path.path.segments.filterIsInstance<ServerPath.Segment.Wildcard>()
            .mapIndexed { index, it ->
                TArg(name = it.name, type = documentable.path.serializers[index], stringType = "String")
            },
        documentable.inputType.takeUnless { it == Unit.serializer() }?.let {
            TArg(name = "input", type = it)
        }?.let(::listOf),
        documentable.primaryAuthName?.takeUnless { skipAuth }?.let {
            TArg(
                name = (overrideUserType ?: it).userTypeTokenName(),
                stringType = "string",
                optional = !documentable.authOptions.options.contains(null).not()
            )
        }?.let(::listOf)
    ).flatten()

    is ApiWebsocket<*, *, *, *, *> -> listOfNotNull(
        documentable.primaryAuthName?.takeUnless { skipAuth }?.let {
            TArg(
                name = (overrideUserType ?: it).userTypeTokenName(),
                stringType = "string",
                optional = !documentable.authOptions.options.contains(null).not()
            )
        }?.let(::listOf),
        documentable.path.path.segments.filterIsInstance<ServerPath.Segment.Wildcard>()
            .map {
                TArg(name = it.name, stringType = "string")
            }
    ).flatten()

    else -> TODO()
}


private fun KSerializer<*>.write(): String =
    nullElement()?.let { it.write() + " | null | undefined" } ?: when {
        this == Unit.serializer() -> "void"
        else -> StringBuilder().also { out ->
            when (descriptor.kind) {
                PrimitiveKind.BOOLEAN -> out.append("boolean")
                PrimitiveKind.BYTE,
                PrimitiveKind.SHORT,
                PrimitiveKind.INT,
                PrimitiveKind.LONG,
                PrimitiveKind.FLOAT,
                PrimitiveKind.DOUBLE -> out.append("number")

                PrimitiveKind.CHAR,
                PrimitiveKind.STRING -> {
                    val cleanName = this.descriptor.simpleSerialName
                    if (cleanName != "String") {
                        out.append(cleanName)
                        this.subSerializers().takeUnless { it.isEmpty() }?.joinToString(", ", "<", ">") { it.write() }
                            ?.let {
                                out.append(it)
                            }
                    } else {
                        out.append("string")
                    }
                }

                StructureKind.LIST -> {
                    out.append("Array<${this.listElement()!!.write()}>")
                }

                StructureKind.MAP -> {
                    out.append("Record")
                    listOf("string", this.mapValueElement()!!.write()).joinToString(", ", "<", ">").let {
                        out.append(it)
                    }
                }

                SerialKind.CONTEXTUAL -> {
                    this.uncontextualize().write().let { out.append(it) }
                }

                is PolymorphicKind,
                StructureKind.OBJECT,
                SerialKind.ENUM,
                StructureKind.CLASS -> {
                    if (descriptor.serialName == "com.lightningkite.serialization.Partial") {
                        out.append("DeepPartial")
                    } else {
                        out.append(descriptor.simpleSerialName)
                    }
                    this.tryTypeParameterSerializers2()?.takeUnless { it.isEmpty() }
                        ?.joinToString(", ", "<", ">") {
                            it.write()
                        }?.let {
                            out.append(it)
                        }
                }
            }
        }.toString().replace("/loose", "")
    }

private fun KSerializer<*>.getGenerics(): Array<KSerializer<*>>? {
    if (descriptor.kind is PolymorphicKind ||
        descriptor.kind is StructureKind.OBJECT ||
        descriptor.kind is SerialKind.ENUM ||
        descriptor.kind is StructureKind.CLASS
    ) {
        return this.tryTypeParameterSerializers2()
    }
    return null
}

private val SerialDescriptor.simpleSerialName: String
    get() = serialName.substringBefore('<').substringAfterLast('.').removeSuffix("?")

private fun String.userTypeTokenName(): String =
    this.substringAfterLast('.').replaceFirstChar { it.lowercase() }.plus("Token")


private val ServerPath.escaped: String
    get() = "/" + segments.joinToString("/") {
        when (it) {
            is ServerPath.Segment.Constant -> it.value
            is ServerPath.Segment.Wildcard -> "\${${it.name}}"
        }
    } + when (after) {
        ServerPath.Afterwards.None -> ""
        ServerPath.Afterwards.TrailingSlash -> "/"
        ServerPath.Afterwards.ChainedWildcard -> "/*"
    }

enum class AutoGeneratedName {
    default,
    query,
    queryPartial,
    detail,
    insertBulk,
    insert,
    upsert,
    bulkReplace,
    replace,
    bulkModify,
    modifyWithDiff,
    modify,
    simplifiedModify,
    bulkDelete,
    delete,
    count,
    groupCount,
    aggregate,
    groupAggregate,
}

val genericEndpointValidators: Map<AutoGeneratedName, (endpoint: ApiEndpoint<*, *, *, *>) -> Boolean> = mapOf(
    AutoGeneratedName.default to { arguments(it, skipAuth = true).isEmpty() },
    AutoGeneratedName.query to {
        val args = arguments(it, skipAuth = true)
        if (args.size != 1) false
        else args[0].type?.write()?.contains("Query") ?: false
    },
    AutoGeneratedName.delete to {
        val args = arguments(it, skipAuth = true)
        args.size == 1 && args[0].type?.write() == "UUID" && it.outputType.write() == "void"
    },
    AutoGeneratedName.detail to {
        val args = arguments(it, skipAuth = true)
        args.size == 1 && args[0].type?.write() == "UUID"
    },
)

fun List<ApiEndpoint<*, *, *, *>>.hasAutoEndpoints(): Boolean {
    return AutoGeneratedName.entries.all {
        val validator = genericEndpointValidators[it] ?: { true }

        this.any { endpoint -> endpoint.functionName == it.name && validator(endpoint) }
    }
}

fun List<ApiEndpoint<*, *, *, *>>.nonAutoGenerated(): List<ApiEndpoint<*, *, *, *>> {
    return this.filterNot { endpoint ->
        AutoGeneratedName.entries.any {
            if (it.name == endpoint.functionName) {
                val validator = genericEndpointValidators[it] ?: { true }
                validator(endpoint)
            } else false
        }
    }
}