package com.lightningkite.lightningserver.typed

import com.lightningkite.UUID
import com.lightningkite.lightningdb.*
import com.lightningkite.serialization.*
import com.lightningkite.serialization.*
import com.lightningkite.lightningserver.core.ServerPath
import com.lightningkite.lightningserver.http.HttpMethod
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.*
import kotlin.reflect.KClass
import kotlin.reflect.KType

fun Documentable.Companion.typescriptSdk(out: Appendable) = with(out) {
    val safeDocumentables =
        endpoints.filter { it.inputType == Unit.serializer() || it.route.method != HttpMethod.GET }.toList()
    appendLine("import { ${fromLightningServerPackage.joinToString()}, apiCall, Path } from '@lightningkite/lightning-server-simplified'")
    appendLine()

    usedTypes
        .filter { it.descriptor.simpleSerialName !in skipFromLsPackage }
        .sortedBy { it.descriptor.simpleSerialName }
        .distinctBy { it.write() }
        .forEach {
            when (it.descriptor.kind) {
                is StructureKind.CLASS -> {
                    if (it is MySealedClassSerializer) return@forEach

                    val genericMap: Map<String, String> = it.getGenerics()
                        ?.withIndex()
                        ?.associate { (index, value) ->
                            value.write() to "T${if (index > 0) index else ""}"
                        } ?: emptyMap()


                    fun String.replaceGenerics(): String =
                        genericMap.entries.fold(this) { acc, (old, new) -> acc.replace(old, new) }

                    appendLine("export interface ${it.write().replaceGenerics()} {")
                    (it.serializableProperties?.map { it.serializer } ?: it.tryChildSerializers()?.toList()
                    ?: listOf()).forEachIndexed { index, sub ->
                        appendLine("    ${it.descriptor.getElementName(index)}: ${sub.write().replaceGenerics()}")
                    }
                    appendLine("}")
                }

                is SerialKind.ENUM -> {
                    append("export enum ")
                    it.write().let { out.append(it) }
                    appendLine(" {")
                    for (index in 0 until it.descriptor.elementsCount) {
                        append("    ")
                        it.descriptor.getElementName(index).first()
                            .let { if (it.isJavaIdentifierStart()) it else '_' }.let { append(it) }
                        it.descriptor.getElementName(index).drop(1)
                            .map { if (it.isJavaIdentifierPart()) it else '_' }.forEach { append(it) }
                        append(" = \"")
                        append(it.descriptor.getElementName(index))
                        append("\",")
                        appendLine()
                    }
                    appendLine("}")
                }

                is PrimitiveKind.STRING -> {
                    if (it.descriptor.simpleSerialName != "String") {
                        appendLine(
                            "export type ${it.descriptor.simpleSerialName} = string  // ${it.descriptor.serialName}".replace(
                                "/loose",
                                ""
                            )
                        )
                    }
                }

                else -> {}
            }
            appendLine()
        }

    appendLine()
    appendLine()


    val byGroup = safeDocumentables.groupBy { it.docGroupIdentifier }
    val groups = byGroup.keys.filterNotNull().sortedBy { it.groupToPartName() }
    appendLine("export interface Api {")
    for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
        append("    ")
        append(entry.functionName)
        this.functionHeader(entry)
        appendLine()
    }
    appendLine()
    for (group in groups) {

        if (byGroup[group].hasAutoEndpoints()) {
            val autoGeneratedInterface =
                byGroup[group]!!.firstOrNull { it.functionName == "detail" }?.outputType?.write()
            append("    readonly ${group.groupToPartName()}: SessionRestEndpointsRaw<${autoGeneratedInterface}>")

            val nonAutogeneratedEndpoints = byGroup[group]!!.filterNot { autoGeneratedNames.contains(it.functionName) }
            if (nonAutogeneratedEndpoints.isNotEmpty()) {
                appendLine(" & {")
                for (entry in nonAutogeneratedEndpoints) {
                    append("        ")
                    append(entry.functionName)
                    this.functionHeader(entry)
                    appendLine()
                }
                appendLine("    }")
            } else {
                appendLine()
            }
        } else {
            appendLine("    readonly ${group.groupToPartName()}: {")
            for (entry in byGroup[group]!!) {
                append("        ")
                append(entry.functionName)
                this.functionHeader(entry)
                appendLine()
            }
            appendLine("    }")
        }
    }
    appendLine("}")

    appendLine()
    appendLine()
    appendLine()

    val byUserType = safeDocumentables.groupBy { it.primaryAuthName }
    val userTypes = byUserType.keys.filterNotNull()
    userTypes.forEach { userType ->
        @Suppress("NAME_SHADOWING") val byGroup =
            ((byUserType[userType] ?: listOf()) + (byUserType[null] ?: listOf())).groupBy { it.docGroupIdentifier }
        @Suppress("NAME_SHADOWING") val groups = byGroup.keys.filterNotNull().sortedBy { it.groupToPartName() }

        val sessionClassName = "${userType.substringAfterLast('.')}Session"
        appendLine("export class $sessionClassName {")
        appendLine("    constructor(public api: Api, public ${userType.userTypeTokenName()}: () => string) {}")
        for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
            appendLine("    ")
            append("    ")
            append(entry.functionName)
            this.functionHeader(entry, skipAuth = true)
            append(" { return this.api.")
            functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
            appendLine(" } ")
        }

        appendLine("""
    private generateAutoEndpoints = <M extends {_id: string}, K extends SessionRestEndpointsRaw<M> = any>(endpoint: K): SessionRestEndpoint<M> => ({
        default: () => endpoint.default(this.${userType.userTypeTokenName()}()),
        query: (input) => endpoint.query(input, this.${userType.userTypeTokenName()}()),
        queryPartial: (input) => endpoint.queryPartial(input, this.${userType.userTypeTokenName()}()),
        detail: (id) => endpoint.detail(id, this.${userType.userTypeTokenName()}()),
        insertBulk: (input) => endpoint.insertBulk(input, this.${userType.userTypeTokenName()}()),
        insert: (input) => endpoint.insert(input, this.${userType.userTypeTokenName()}()),
        upsert: (id, input) => endpoint.upsert(id, input, this.${userType.userTypeTokenName()}()),
        bulkReplace: (input) => endpoint.bulkReplace(input, this.${userType.userTypeTokenName()}()),
        replace: (id, input) => endpoint.replace(id, input, this.${userType.userTypeTokenName()}()),
        bulkModify: (input) => endpoint.bulkModify(input, this.${userType.userTypeTokenName()}()),
        modifyWithDiff: (id, input) => endpoint.modifyWithDiff(id, input, this.${userType.userTypeTokenName()}()),
        modify: (id, input) => endpoint.modify(id, input, this.${userType.userTypeTokenName()}()),
        simplifiedModify: (id, input) => endpoint.simplifiedModify(id, input, this.${userType.userTypeTokenName()}()),
        bulkDelete: (input) => endpoint.bulkDelete(input, this.${userType.userTypeTokenName()}()),
        delete: (id) => endpoint.delete(id, this.${userType.userTypeTokenName()}()),
        count: (input) => endpoint.count(input, this.${userType.userTypeTokenName()}()),
        groupCount: (input) => endpoint.groupCount(input, this.${userType.userTypeTokenName()}()),
        aggregate: (input) => endpoint.aggregate(input, this.${userType.userTypeTokenName()}()),
        groupAggregate: (input) => endpoint.groupAggregate(input, this.${userType.userTypeTokenName()}()),
    })
        """)
        appendLine()

        for (group in groups) {
            if (byGroup[group].hasAutoEndpoints()) {
                val autoGeneratedInterface =
                    byGroup[group]!!.firstOrNull { it.functionName == "detail" }?.outputType?.write()
                val nonAutogeneratedEndpoints = byGroup[group]!!.filterNot { autoGeneratedNames.contains(it.functionName) }
                appendLine("    readonly ${group.groupToPartName()} = {")
                append("        ")
                appendLine("...this.generateAutoEndpoints<${autoGeneratedInterface}>(this.api.${group.groupToPartName()}),")
                for (entry in nonAutogeneratedEndpoints) {
                    append("        ")
                    append(entry.functionName)
                    append(": ")
                    this.functionHeader(entry, skipAuth = true)
                    append(" => { return this.api.")
                    append(group.groupToPartName())
                    append(".")
                    functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
                    appendLine(" }, ")
                }
                appendLine("    }")
            } else {
                appendLine("    readonly ${group.groupToPartName()} = {")
                for (entry in byGroup[group]!!) {
                    append("        ")
                    append(entry.functionName)
                    append(": ")
                    this.functionHeader(entry, skipAuth = true)
                    append(" => { return this.api.")
                    append(group.groupToPartName())
                    append(".")
                    functionCall(entry, skipAuth = false, authUsesThis = true, overrideUserType = userType)
                    appendLine(" }, ")
                }
                appendLine("    }")
            }


        }
        appendLine("}")
        appendLine()
    }

    appendLine()
    appendLine()
    appendLine()


    appendLine("export class LiveApi implements Api {")
    appendLine("    public constructor(public httpUrl: string, public socketUrl: string = httpUrl, public extraHeaders: Record<string, string> = {}, public responseInterceptors?: (x: Response)=>Response) {}")

    appendLine("""
    private apiCallHelper = <T, R>(
        subPath: string,
        method: string,
        input: T | undefined,
        userToken: string | undefined
    ): Promise<R> => {
        return apiCall<T>(
            `${"$"}{this.httpUrl}${"$"}{subPath}`,
            input as T,
            {
                method,
                headers: userToken
                    ? { ...this.extraHeaders, Authorization: `Bearer $\{userToken}` }
                    : this.extraHeaders,
            },
            undefined,
            this.responseInterceptors
        ).then((x) => x.json());
    };

    private generateEndpoints = <T extends {_id: string}>(path: string): SessionRestEndpointsRaw<T>  => ({
        default: (userToken) => this.apiCallHelper(`${"$"}{path}/_default_`, "GET", undefined, userToken),
        query: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/query`, "POST", input, userToken),
        queryPartial: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/query-partial`, "POST", input, userToken),
        detail: (id, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}`, "GET", undefined, userToken),
        insertBulk: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/bulk`, "POST", input, userToken),
        insert: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest`, "POST", input, userToken),
        upsert: (id, input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}`, "POST", input, userToken),
        bulkReplace: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest`, "PUT", input, userToken),
        replace: (id, input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}`, "PUT", input, userToken),
        bulkModify: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/bulk`, "PATCH", input, userToken),
        modifyWithDiff: (id, input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}/delta`, "PATCH", input, userToken),
        modify: (id, input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}`, "PATCH", input, userToken),
        simplifiedModify: (id, input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}/simplified`, "PATCH", input, userToken),
        bulkDelete: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/bulk-delete`, "POST", input, userToken),
        delete: (id, userToken) => this.apiCallHelper(`${"$"}{path}/rest/${"$"}{id}`, "DELETE", undefined, userToken),
        count: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/count`, "POST", input, userToken),
        groupCount: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/group-count`, "POST", input, userToken),
        aggregate: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/aggregate`, "POST", input, userToken),
        groupAggregate: (input, userToken) => this.apiCallHelper(`${"$"}{path}/rest/group-aggregate`, "POST", input, userToken),
    });
    """)
    appendLine()
    appendLine()

    for (entry in byGroup[null]?.sortedBy { it.functionName } ?: listOf()) {
        append("    ")
        append(entry.functionName)
        this.functionHeader(entry, skipAuth = false)
        appendLine(" {")
        val hasInput = entry.inputType != Unit.serializer()
        appendLine("        return this.apiCallHelper<${entry.inputType.write()}, ${entry.outputType.write()}>(")
        appendLine("            `${entry.path.path.escaped}`,")
        appendLine("            \"${entry.route.method}\",")
        appendLine("            ${if (hasInput) "input" else "undefined"},")
        appendLine("            ${entry.primaryAuthName?.userTypeTokenName() ?: "undefined"},")
        appendLine("        )")
        appendLine("    }")
    }




    for (group in groups.sortedBy { it.groupToPartName() }) {
        appendLine("    readonly ${group.groupToPartName()} = {")

        val explicitEndpoints = if (byGroup[group]!!.hasAutoEndpoints()) byGroup[group]!!.filterNot { autoGeneratedNames.contains(it.functionName) } else byGroup[group]!!

        if (byGroup[group]!!.hasAutoEndpoints()) {
            val autoGeneratedInterface =
                byGroup[group]!!.firstOrNull { it.functionName == "detail" }?.outputType?.write()
            append("        ")
            appendLine("...this.generateEndpoints<${autoGeneratedInterface}>(\"/${group.groupToPartName()}\"),")
        }

        for (entry in explicitEndpoints) {
            appendLine("        ")
            append("        ")
            append(entry.functionName)
            append(": ")
            this.functionHeader(entry, skipAuth = false)
            appendLine(" => {")
            val hasInput = entry.inputType != Unit.serializer()
            appendLine("            return this.apiCallHelper<${entry.inputType.write()}, ${entry.outputType.write()}>(")
            appendLine("                `${entry.path.path.escaped}`,")
            appendLine("                \"${entry.route.method}\",")
            appendLine("                ${if (hasInput) "input" else "undefined"},")
            appendLine("                ${entry.primaryAuthName?.userTypeTokenName() ?: "undefined"},")
            appendLine("            )")
            appendLine("        },")
        }
        appendLine("    }")
    }
    appendLine("}")
    appendLine()
}


private val fromLightningServerPackage = setOf(
    "Query",
    "MassModification",
    "EntryChange",
    "ListChange",
    "Modification",
    "Condition",
    "GroupCountQuery",
    "AggregateQuery",
    "GroupAggregateQuery",
    "Aggregate",
    "SortPart",
    "DataClassPath",
    "DataClassPathPartial",
    "QueryPartial",
    "DeepPartial",
    "SessionRestEndpoint",
    "SessionRestEndpointsRaw"
)
private val skipFromLsPackage = setOf(
    "Partial",
) + fromLightningServerPackage

private fun String.groupToPartName(): String = replaceFirstChar { it.lowercase() }

@Suppress("UNCHECKED_CAST")
private fun KType?.userTypeTokenName(): String = (this?.classifier as? KClass<Any>)?.userTypeTokenName() ?: "token"
private fun KClass<*>.userTypeTokenName(): String =
    simpleName?.replaceFirstChar { it.lowercase() }?.plus("Token") ?: "token"

private fun Appendable.functionHeader(
    documentable: Documentable,
    skipAuth: Boolean = false,
    overrideUserType: String? = null
) {
    append("(")
    var argComma = false
    arguments(documentable, skipAuth, overrideUserType).forEach {
        if (argComma) append(", ")
        else argComma = true
        append(it.name)
        if (it.optional) append("?")
        append(": ")
        it.type?.write()?.let { append(it) } ?: it.stringType?.let { append(it) }
    }
    append("): ")
    when (documentable) {
        is ApiEndpoint<*, *, *, *> -> {
            append("Promise<")
            documentable.outputType.write().let { append(it) }
            append(">")
        }

        is ApiWebsocket<*, *, *, *> -> {
            append("Observable<WebSocketIsh<")
            documentable.inputType.write().let { append(it) }
            append(", ")
            documentable.outputType.write().let { append(it) }
            append(">>")
        }

        else -> TODO()
    }
}

private fun Appendable.functionCall(
    documentable: Documentable,
    skipAuth: Boolean = false,
    authUsesThis: Boolean = false,
    overrideUserType: String? = null
) {
    append("${documentable.functionName}(")
    var argComma = false
    arguments(documentable, skipAuth, overrideUserType).forEach {
        if (argComma) append(", ")
        else argComma = true
        if (it.name == documentable.primaryAuthName?.userTypeTokenName() && authUsesThis) {
            append("this.${it.name}()")
        } else {
            append(it.name)
        }
    }
    append(")")
}

private data class TArg(
    val name: String,
    val type: KSerializer<*>? = null,
    val stringType: String? = null,
    val default: String? = null,
    val optional: Boolean = false
)

private fun arguments(
    documentable: Documentable,
    skipAuth: Boolean = false,
    overrideUserType: String? = null
): List<TArg> = when (documentable) {
    is ApiEndpoint<*, *, *, *> -> listOfNotNull(
        documentable.path.path.segments.filterIsInstance<ServerPath.Segment.Wildcard>()
            .mapIndexed { index, it ->
                TArg(name = it.name, type = documentable.path.serializers[index], stringType = "String")
            },
        documentable.inputType.takeUnless { it == Unit.serializer() }?.let {
            TArg(name = "input", type = it)
        }?.let(::listOf),
        documentable.primaryAuthName?.takeUnless { skipAuth }?.let {
            TArg(
                name = (overrideUserType ?: it).userTypeTokenName(),
                stringType = "string",
                optional = !documentable.authOptions.options.contains(null).not()
            )
        }?.let(::listOf)
    ).flatten()

    is ApiWebsocket<*, *, *, *> -> listOfNotNull(
        documentable.primaryAuthName?.takeUnless { skipAuth }?.let {
            TArg(
                name = (overrideUserType ?: it).userTypeTokenName(),
                stringType = "string",
                optional = !documentable.authOptions.options.contains(null).not()
            )
        }?.let(::listOf),
        documentable.path.path.segments.filterIsInstance<ServerPath.Segment.Wildcard>()
            .map {
                TArg(name = it.name, stringType = "string")
            }
    ).flatten()

    else -> TODO()
}


private fun KSerializer<*>.write(): String =
    nullElement()?.let { it.write() + " | null | undefined" } ?: when {
        this == Unit.serializer() -> "void"
        else -> StringBuilder().also { out ->
            when (descriptor.kind) {
                PrimitiveKind.BOOLEAN -> out.append("boolean")
                PrimitiveKind.BYTE,
                PrimitiveKind.SHORT,
                PrimitiveKind.INT,
                PrimitiveKind.LONG,
                PrimitiveKind.FLOAT,
                PrimitiveKind.DOUBLE -> out.append("number")

                PrimitiveKind.CHAR,
                PrimitiveKind.STRING -> {
                    val cleanName = this.descriptor.simpleSerialName
                    if (cleanName != "String") {
                        out.append(cleanName)
                        this.subSerializers().takeUnless { it.isEmpty() }?.joinToString(", ", "<", ">") { it.write() }
                            ?.let {
                                out.append(it)
                            }
                    } else {
                        out.append("string")
                    }
                }

                StructureKind.LIST -> {
                    out.append("Array<${this.listElement()!!.write()}>")
                }

                StructureKind.MAP -> {
                    out.append("Record")
                    listOf("string", this.mapValueElement()!!.write()).joinToString(", ", "<", ">").let {
                        out.append(it)
                    }
                }

                SerialKind.CONTEXTUAL -> {
                    this.uncontextualize().write().let { out.append(it) }
                }

                is PolymorphicKind,
                StructureKind.OBJECT,
                SerialKind.ENUM,
                StructureKind.CLASS -> {
                    if (descriptor.serialName == "com.lightningkite.serialization.Partial") {
                        out.append("DeepPartial")
                    } else {
                        out.append(descriptor.simpleSerialName)
                    }
                    this.tryTypeParameterSerializers2()?.takeUnless { it.isEmpty() }
                        ?.joinToString(", ", "<", ">") {
                            it.write()
                        }?.let {
                            out.append(it)
                        }
                }
            }
        }.toString().replace("/loose", "")
    }

private fun KSerializer<*>.getGenerics(): Array<KSerializer<*>>? {
    if (descriptor.kind is PolymorphicKind ||
        descriptor.kind is StructureKind.OBJECT ||
        descriptor.kind is SerialKind.ENUM ||
        descriptor.kind is StructureKind.CLASS
    ) {
        return this.tryTypeParameterSerializers2()
    }
    return null
}

private val SerialDescriptor.simpleSerialName: String
    get() = serialName.substringBefore('<').substringAfterLast('.').removeSuffix("?")

private fun String.userTypeTokenName(): String =
    this.substringAfterLast('.').replaceFirstChar { it.lowercase() }.plus("Token")


private val ServerPath.escaped: String
    get() = "/" + segments.joinToString("/") {
        when (it) {
            is ServerPath.Segment.Constant -> it.value
            is ServerPath.Segment.Wildcard -> "\${${it.name}}"
        }
    } + when (after) {
        ServerPath.Afterwards.None -> ""
        ServerPath.Afterwards.TrailingSlash -> "/"
        ServerPath.Afterwards.ChainedWildcard -> "/*"
    }


val autoGeneratedNames = listOf(
    "default",
    "query",
    "queryPartial",
    "detail",
    "insertBulk",
    "insert",
    "upsert",
    "bulkReplace",
    "replace",
    "bulkModify",
    "modifyWithDiff",
    "modify",
    "simplifiedModify",
    "bulkDelete",
    "delete",
    "count",
    "groupCount",
    "aggregate",
    "groupAggregate",
)

fun List<ApiEndpoint<*, *, *, *>>?.hasAutoEndpoints(): Boolean = this?.let {
    val hasAllEndpoints =
        autoGeneratedNames.all { auto -> this.firstOrNull { it.functionName == auto } != null }

    val detailIsValid = this.firstOrNull {
        if (it.functionName == "detail" && arguments(it).isNotEmpty()) {
            (arguments(it).firstOrNull { it.type?.write() == "UUID" } != null) && arguments(it).size == 2
        } else false
    } != null

    val deleteIsValid = this.firstOrNull {
        if (it.functionName == "delete") {
            it.outputType.write() == "void"
        } else false
    } != null

    return hasAllEndpoints && detailIsValid && deleteIsValid
} ?: false