// Package: com.lightningkite.ktordb.mock
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import RxSwiftPlus
import Foundation

public class MockObserveModelApi<Model : HasId> : ObserveModelApi<Model> {
    public var table: MockTable<Model>
    public init(table: MockTable<Model>) {
        self.table = table
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public func observe(_ query: Query<Model>) -> Observable<Array<Model>> {
        return self.table.observe(query.condition).startWith(self.table.asList().filter({ (item) -> Bool in query.condition.invoke(on: item) }))
    }
}
