
[versions]
agp = "8.12.3"
androidDesugaring = "2.1.5"
awsVersion = "2.41.20"
bouncyCastle = "1.83"
coroutines = "1.10.2"
cryptographyKotlin = "0.5.0"
dokka = "2.1.0"
dynamodb = "2.41.20"
graalVmNative = "0.11.4"
kotlin = "2.2.20"
kotlinHtmlJvm = "0.12.0"
kotlinXDatetime = "0.7.1"
kotlinXIO = "0.8.2"
kotlinXSerialization = "1.9.0"
kotlinerCli = "1.0.5"
ksp = "2.2.20-2.0.4"
ktor = "3.4.0"
lambdaJavaCore = "1.4.0"
lambdaJavaEvents = "3.16.1"
lkGradleHelpers = "4.0.6"
netty = "4.1.114.Final"
oneTimePass = "2.4.1"
orgCrac = "0.1.3"
proguard = "7.8.2"
scrimage = "4.3.3"
serializationLibs = "1.9.0"
serviceAbstractions = "0.0.1-177"
shadow = "8.1.1"
vanniktechMavenPublish = "0.35.0"
webauthn4jCore = "0.29.4.RELEASE"
kover = "0.9.7"

[libraries]
androidDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = { ref = "androidDesugaring" } }
awsApiGateway = { module = "software.amazon.awssdk:apigatewaymanagementapi", version = { ref = "awsVersion" } }
awsLambda = { module = "software.amazon.awssdk:lambda", version = { ref = "awsVersion" } }
awsS3 = { module = "software.amazon.awssdk:s3", version = { ref = "awsVersion" } }
awsSecretsManager = { module = "software.amazon.awssdk:secretsmanager", version = { ref = "awsVersion" } }
bouncyCastleBcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version = { ref = "bouncyCastle" } }
bouncyCastleBcprov = { module = "org.bouncycastle:bcprov-jdk18on", version = { ref = "bouncyCastle" } }
coroutinesJdk = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version = { ref = "coroutines" } }
coroutinesReactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version = { ref = "coroutines" } }
dynamodb = { module = "software.amazon.awssdk:dynamodb", version = { ref = "dynamodb" } }
kotlinHtmlJvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = { ref = "kotlinHtmlJvm" } }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version = { ref = "kotlin" } }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version = { ref = "kotlin" } }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version = { ref = "kotlin" } }
kotlinXDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = { ref = "kotlinXDatetime" } }
kotlinXIO = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = { ref = "kotlinXIO" } }
kotlinXJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = { ref = "kotlinXSerialization" } }
kotlinXJsonIO = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-io", version = { ref = "kotlinXSerialization" } }
kotlinerCli = { module = "com.lightningkite:kotliner-cli", version = { ref = "kotlinerCli" } }
kotlinxCryptoCore = { module = "dev.whyoleg.cryptography:cryptography-core", version = { ref = "cryptographyKotlin" } }
kotlinxCryptoOptimal = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal", version = { ref = "cryptographyKotlin" } }
ktorCallLogging = { module = "io.ktor:ktor-server-call-logging", version = { ref = "ktor" } }
ktorCioJvm = { module = "io.ktor:ktor-server-cio-jvm", version = { ref = "ktor" } }
ktorCore = { module = "io.ktor:ktor-server-core-jvm", version = { ref = "ktor" } }
ktorJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version = { ref = "ktor" } }
ktorNetty = { module = "io.ktor:ktor-server-netty-jvm", version = { ref = "ktor" } }
ktorTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version = { ref = "ktor" } }
ktorWebsockets = { module = "io.ktor:ktor-server-websockets-jvm", version = { ref = "ktor" } }
lambdaJavaCore = { module = "com.amazonaws:aws-lambda-java-core", version = { ref = "lambdaJavaCore" } }
lambdaJavaEvents = { module = "com.amazonaws:aws-lambda-java-events", version = { ref = "lambdaJavaEvents" } }
lkGradleHelpers = { module = "com.lightningkite:lk-gradle-helpers", version = { ref = "lkGradleHelpers" } }
nettyBom = { module = "io.netty:netty-bom", version = { ref = "netty" } }
nettyBuffer = { module = "io.netty:netty-buffer", version = "0.0.0" }
nettyCodec = { module = "io.netty:netty-codec", version = "0.0.0" }
nettyCodecHttp = { module = "io.netty:netty-codec-http", version = "0.0.0" }
nettyHandler = { module = "io.netty:netty-handler", version = "0.0.0" }
nettyTransport = { module = "io.netty:netty-transport", version = "0.0.0" }
nettyTransportClassesEpoll = { module = "io.netty:netty-transport-classes-epoll", version = "0.0.0" }
nettyTransportClassesKqueue = { module = "io.netty:netty-transport-classes-kqueue", version = "0.0.0" }
oneTimePass = { module = "dev.turingcomplete:kotlin-onetimepassword", version = { ref = "oneTimePass" } }
orgCrac = { module = "io.github.crac:org-crac", version = { ref = "orgCrac" } }
proguard = { module = "com.guardsquare:proguard-gradle", version = { ref = "proguard" } }
scrimage = { module = "com.sksamuel.scrimage:scrimage-core", version = { ref = "scrimage" } }
scrimageFormats = { module = "com.sksamuel.scrimage:scrimage-formats-extra", version = { ref = "scrimage" } }
scrimageWebP = { module = "com.sksamuel.scrimage:scrimage-webp", version = { ref = "scrimage" } }
serializationProperties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version = { ref = "serializationLibs" } }
serializationProtobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version = { ref = "serializationLibs" } }
serviceAbstractionsAiKoog = { module = "com.lightningkite.services:ai-koog", version = { ref = "serviceAbstractions" } }
serviceAbstractionsAiKoogAwsOpensearch = { module = "com.lightningkite.services:ai-koog-aws-opensearch", version = { ref = "serviceAbstractions" } }
serviceAbstractionsAwsClient = { module = "com.lightningkite.services:aws-client", version = { ref = "serviceAbstractions" } }
serviceAbstractionsBasis = { module = "com.lightningkite.services:basis", version = { ref = "serviceAbstractions" } }
serviceAbstractionsCache = { module = "com.lightningkite.services:cache", version = { ref = "serviceAbstractions" } }
serviceAbstractionsCacheDynamodb = { module = "com.lightningkite.services:cache-dynamodb", version = { ref = "serviceAbstractions" } }
serviceAbstractionsCacheMemcached = { module = "com.lightningkite.services:cache-memcached", version = { ref = "serviceAbstractions" } }
serviceAbstractionsCacheRedis = { module = "com.lightningkite.services:cache-redis", version = { ref = "serviceAbstractions" } }
serviceAbstractionsCacheTest = { module = "com.lightningkite.services:cache-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsData = { module = "com.lightningkite.services:data", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabase = { module = "com.lightningkite.services:database", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseCassandra = { module = "com.lightningkite.services:database-cassandra", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseJsonfile = { module = "com.lightningkite.services:database-jsonfile", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseMongodb = { module = "com.lightningkite.services:database-mongodb", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabasePostgres = { module = "com.lightningkite.services:database-postgres", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseProcessor = { module = "com.lightningkite.services:database-processor", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseShared = { module = "com.lightningkite.services:database-shared", version = { ref = "serviceAbstractions" } }
serviceAbstractionsDatabaseTest = { module = "com.lightningkite.services:database-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmail = { module = "com.lightningkite.services:email", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailJavasmtp = { module = "com.lightningkite.services:email-javasmtp", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailTest = { module = "com.lightningkite.services:email-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsFiles = { module = "com.lightningkite.services:files", version = { ref = "serviceAbstractions" } }
serviceAbstractionsFilesClamav = { module = "com.lightningkite.services:files-clamav", version = { ref = "serviceAbstractions" } }
serviceAbstractionsFilesClient = { module = "com.lightningkite.services:files-client", version = { ref = "serviceAbstractions" } }
serviceAbstractionsFilesS3 = { module = "com.lightningkite.services:files-s3", version = { ref = "serviceAbstractions" } }
serviceAbstractionsFilesTest = { module = "com.lightningkite.services:files-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsHttpClient = { module = "com.lightningkite.services:http-client", version = { ref = "serviceAbstractions" } }
serviceAbstractionsNotifications = { module = "com.lightningkite.services:notifications", version = { ref = "serviceAbstractions" } }
serviceAbstractionsNotificationsFcm = { module = "com.lightningkite.services:notifications-fcm", version = { ref = "serviceAbstractions" } }
serviceAbstractionsNotificationsTest = { module = "com.lightningkite.services:notifications-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsOtelJvm = { module = "com.lightningkite.services:otel-jvm", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPubsub = { module = "com.lightningkite.services:pubsub", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPubsubRedis = { module = "com.lightningkite.services:pubsub-redis", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPubsubAws = { module = "com.lightningkite.services:pubsub-aws", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPubsubTest = { module = "com.lightningkite.services:pubsub-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsShouldBeStandardLibrary = { module = "com.lightningkite.services:should-be-standard-library", version = { ref = "serviceAbstractions" } }
serviceAbstractionsSms = { module = "com.lightningkite.services:sms", version = { ref = "serviceAbstractions" } }
serviceAbstractionsSmsTest = { module = "com.lightningkite.services:sms-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsSmsTwilio = { module = "com.lightningkite.services:sms-twilio", version = { ref = "serviceAbstractions" } }
serviceAbstractionsTest = { module = "com.lightningkite.services:test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailInbound = { module = "com.lightningkite.services:email-inbound", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailInboundSendgrid = { module = "com.lightningkite.services:email-inbound-sendgrid", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailInboundMailgun = { module = "com.lightningkite.services:email-inbound-mailgun", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailInboundSes = { module = "com.lightningkite.services:email-inbound-ses", version = { ref = "serviceAbstractions" } }
serviceAbstractionsEmailInboundImap = { module = "com.lightningkite.services:email-inbound-imap", version = { ref = "serviceAbstractions" } }
serviceAbstractionsSmsInbound = { module = "com.lightningkite.services:sms-inbound", version = { ref = "serviceAbstractions" } }
serviceAbstractionsSmsInboundTwilio = { module = "com.lightningkite.services:sms-inbound-twilio", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPhonecall = { module = "com.lightningkite.services:phonecall", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPhonecallTwilio = { module = "com.lightningkite.services:phonecall-twilio", version = { ref = "serviceAbstractions" } }
serviceAbstractionsPhonecallTest = { module = "com.lightningkite.services:phonecall-test", version = { ref = "serviceAbstractions" } }
serviceAbstractionsVoiceagent = { module = "com.lightningkite.services:voiceagent", version = { ref = "serviceAbstractions" } }
serviceAbstractionsVoiceagentOpenai = { module = "com.lightningkite.services:voiceagent-openai", version = { ref = "serviceAbstractions" } }
serviceAbstractionsVoiceagentPhonecall = { module = "com.lightningkite.services:voiceagent-phonecall", version = { ref = "serviceAbstractions" } }
webauthn4jCore = { module = "com.webauthn4j:webauthn4j-core", version = { ref = "webauthn4jCore" } }

[plugins]
androidApp = { id = "com.android.application", version = { ref = "agp" } }
androidLibrary = { id = "com.android.library", version = { ref = "agp" } }
dokka = { id = "org.jetbrains.dokka", version = { ref = "dokka" } }
graalVmNative = { id = "org.graalvm.buildtools.native", version = { ref = "graalVmNative" } }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = { ref = "kotlin" } }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = { ref = "kotlin" } }
ksp = { id = "com.google.devtools.ksp", version = { ref = "ksp" } }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = { ref = "kotlin" } }
shadow = { id = "com.github.johnrengelman.shadow", version = { ref = "shadow" } }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version = { ref = "vanniktechMavenPublish" } }
kover = { id = "org.jetbrains.kotlinx.kover", version = { ref = "kover" } }