// Package: com.lightningkite.ktordb.mock
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public class ItemNotFound : Exception {
    public init(message: String) {
        super.init(message)
        //Necessary properties should be initialized now
    }
}
