package com.lightningkite.lightningserver.encryption

import com.lightningkite.lightningserver.metrics.MetricType
import com.lightningkite.lightningserver.metrics.MetricUnit
import com.lightningkite.lightningserver.metrics.Metrics
import io.ktor.util.*
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec


private const val pbkdf2Prefix = "PBKDF2WithHmacSHA512."
private const val sha256Prefix = "SHA256."

object SecureHash {
    val metricsKey = MetricType("Secure Hashing", MetricUnit.Milliseconds)
}

/**
 * Securely hashes a string using PBKDF2 with 100,000 iterations.
 * This is appropriate for password storage where the input may be low-entropy.
 * For high-entropy random secrets (like session tokens), use [fastHash] instead.
 */
fun String.secureHash(): String {
    if (this.startsWith(pbkdf2Prefix)) return this
    if (this.isEmpty()) return ""
    val start = System.nanoTime()
    val salt = ByteArray(16)
    SecureRandom().nextBytes(salt)
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    Metrics.report(SecureHash.metricsKey, tookNs / 1000000.0)
    return pbkdf2Prefix + salt.encodeBase64() + "." + key.encoded.encodeBase64()
}

/**
 * Fast hash using SHA-256 with a random salt.
 * This is appropriate for high-entropy random secrets (like session tokens)
 * where the slow iterations of PBKDF2 provide no additional security benefit.
 *
 * DO NOT use this for password hashing - use [secureHash] instead.
 */
fun String.fastHash(): String {
    if (this.startsWith(sha256Prefix)) return this
    if (this.isEmpty()) return ""
    val salt = ByteArray(16)
    SecureRandom().nextBytes(salt)
    val digest = MessageDigest.getInstance("SHA-256")
    digest.update(salt)
    digest.update(this.toByteArray(Charsets.UTF_8))
    return sha256Prefix + salt.encodeBase64() + "." + digest.digest().encodeBase64()
}

/**
 * Checks hashes generated by [secureHash] or [fastHash].
 * Automatically detects the hash format based on prefix.
 */
fun String.checkAgainstHash(againstHash: String): Boolean {
    if (againstHash.isEmpty()) return false
    return when {
        againstHash.startsWith(sha256Prefix) -> checkAgainstFastHash(againstHash)
        againstHash.startsWith(pbkdf2Prefix) -> checkAgainstPbkdf2Hash(againstHash)
        else -> false
    }
}

private fun String.checkAgainstFastHash(againstHash: String): Boolean {
    val against = againstHash.removePrefix(sha256Prefix)
    val salt = against.substringBefore('.').decodeBase64Bytes()
    val expectedHash = against.substringAfter('.')
    val digest = MessageDigest.getInstance("SHA-256")
    digest.update(salt)
    digest.update(this.toByteArray(Charsets.UTF_8))
    return digest.digest().encodeBase64() == expectedHash
}

private fun String.checkAgainstPbkdf2Hash(againstHash: String): Boolean {
    val against = againstHash.removePrefix(pbkdf2Prefix)
    val start = System.nanoTime()
    val salt = against.substringBefore('.').decodeBase64Bytes()
    val rest = against.substringAfter('.')
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    Metrics.report(SecureHash.metricsKey, tookNs / 1000000.0)
    return key.encoded.encodeBase64() == rest
}

/**
 * Returns true if this hash string uses the slow PBKDF2 format.
 * Useful for determining if a hash should be migrated to the faster format.
 */
fun String.isSlowHash(): Boolean = this.startsWith(pbkdf2Prefix)
