use_frameworks!

platform :ios, '11.0'

target 'BatteriesClient_Example' do
  pod 'BatteriesClient', :path => '../../'
  pod 'KhrysalisRuntime', :path => '../../../khrysalis/KhrysalisRuntime.podspec'
  pod 'XmlToXibRuntime', :path => '../../../android-xml-to-ios-xib/XmlToXibRuntime.podspec'
  pod 'RxSwift', :path => '../../../RxSwift/RxSwift.podspec'
  pod 'RxSwiftPlus', :path => '../../../RxSwiftPlus/RxSwiftPlus.podspec'
  pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'

  target 'BatteriesClient_Tests' do
    inherit! :search_paths

    
  end
end
