package com.lightningkite.lightningserver.encryption

import dev.whyoleg.cryptography.BinarySize
import dev.whyoleg.cryptography.BinarySize.Companion.bits
import dev.whyoleg.cryptography.BinarySize.Companion.bytes
import dev.whyoleg.cryptography.CryptographyAlgorithmId
import dev.whyoleg.cryptography.CryptographyProvider
import dev.whyoleg.cryptography.CryptographyProviderApi
import dev.whyoleg.cryptography.DelicateCryptographyApi
import dev.whyoleg.cryptography.algorithms.Digest
import dev.whyoleg.cryptography.algorithms.PBKDF2
import dev.whyoleg.cryptography.algorithms.SHA1
import dev.whyoleg.cryptography.algorithms.SHA224
import dev.whyoleg.cryptography.algorithms.SHA256
import dev.whyoleg.cryptography.algorithms.SHA384
import dev.whyoleg.cryptography.algorithms.SHA3_224
import dev.whyoleg.cryptography.algorithms.SHA3_256
import dev.whyoleg.cryptography.algorithms.SHA3_384
import dev.whyoleg.cryptography.algorithms.SHA3_512
import dev.whyoleg.cryptography.algorithms.SHA512
import dev.whyoleg.cryptography.operations.SecretDerivation
import dev.whyoleg.cryptography.random.CryptographyRandom
import kotlinx.io.bytestring.encodeToByteString
import java.lang.IllegalStateException
import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import kotlin.io.encoding.Base64


private const val prefix = "PBKDF2WithHmacSHA512."

private suspend fun String.hash(salt: ByteArray): ByteArray =
    CryptographyProvider.Default
        .get(PBKDF2)
        .secretDerivation(
            SHA512,
            iterations = 100_000,
            outputSize = 512.bits,
            salt = salt
        )
    .deriveSecretToByteArray(this.encodeToByteString())

/**
 * Securely hashes a string in a way that could be used for password storage.
 *
 * **This is a very expensive operation and should only be called once**
 */
public suspend fun String.secureHash(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""

    val salt = CryptographyRandom.nextBytes(16)
    val secret = this.hash(salt)

    return prefix + Base64.encode(salt) + '.' + Base64.encode(secret)
}

/**
 * Checks hashes generated by [secureHash].
 *
 * **This is a very expensive operation and should only be called once**
 */
public suspend fun String.checkAgainstHash(hash: String): Boolean {
    if (!hash.startsWith(prefix)) return false
    if (hash.isEmpty()) return false

    val data = hash.removePrefix(prefix)
    val salt = Base64.decode(data.substringBefore('.'))
    val secret = Base64.decode(data.substringAfter('.'))

    return this.hash(salt) contentEquals secret
}


/**
 * Securely hashes a string in a way that could be used for password storage.
 *
 * **This is a very expensive operation and should only be called once**
 */
internal suspend fun String.secureHashJava(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""
    val start = System.nanoTime()
    val salt = ByteArray(16)
    SecureRandom().nextBytes(salt)
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100_000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    return prefix + Base64.encode(salt) + "." + Base64.encode(key.encoded)
}

/**
 * Checks hashes generated by [secureHash].
 *
 * **This is a very expensive operation and should only be called once**
 */
internal suspend fun String.checkAgainstHashJava(againstHash: String): Boolean {
    if (againstHash.isEmpty()) return false
    val against = againstHash.removePrefix(prefix)
    val start = System.nanoTime()
    val salt = Base64.decode(against.substringBefore('.'))
    val rest = against.substringAfter('.')
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100_000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    return Base64.encode(key.encoded) == rest
}
