package com.lightningkite.lightningserver.encryption

import dev.whyoleg.cryptography.BinarySize.Companion.bytes
import dev.whyoleg.cryptography.CryptographyProvider
import dev.whyoleg.cryptography.algorithms.PBKDF2
import dev.whyoleg.cryptography.algorithms.SHA512
import dev.whyoleg.cryptography.random.CryptographyRandom
import kotlinx.io.bytestring.encodeToByteString
import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import kotlin.io.encoding.Base64


private const val prefix = "PBKDF2WithHmacSHA512."

private suspend fun String.hash(salt: ByteArray): ByteArray = CryptographyProvider.Default
    .get(PBKDF2)
    .secretDerivation(
        SHA512,
        iterations = 100_000,
        outputSize = 512.bytes,
        salt
    )
    .deriveSecretToByteArray(this.encodeToByteString())

/**
 * Securely hashes a string in a way that could be used for password storage.
 */
public suspend fun String.secureHash(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""

    val salt = CryptographyRandom.nextBytes(16)
    val secret = hash(salt)

    return prefix + Base64.encode(salt) + '.' + Base64.encode(secret)
}

/**
 * Checks hashes generated by [secureHash].
 */
public suspend fun String.checkAgainstHash(hash: String): Boolean {
    if (!hash.startsWith(prefix)) return false
    if (hash.isEmpty()) return false

    val data = hash.removePrefix(prefix)
    val salt = Base64.decode(data.substringBefore('.'))
    val secret = Base64.decode(data.substringAfter('.'))

    return hash(salt) contentEquals secret
}
