/**
 * Password hashing utilities using PBKDF2-HMAC-SHA512.
 *
 * This file provides functions for securely hashing and verifying passwords.
 * These functions are intentionally slow (100,000 iterations) to resist
 * brute-force attacks. They should only be called once per authentication attempt.
 */
package com.lightningkite.lightningserver.encryption

import dev.whyoleg.cryptography.BinarySize
import dev.whyoleg.cryptography.BinarySize.Companion.bits
import dev.whyoleg.cryptography.BinarySize.Companion.bytes
import dev.whyoleg.cryptography.CryptographyAlgorithmId
import dev.whyoleg.cryptography.CryptographyProvider
import dev.whyoleg.cryptography.CryptographyProviderApi
import dev.whyoleg.cryptography.DelicateCryptographyApi
import dev.whyoleg.cryptography.algorithms.Digest
import dev.whyoleg.cryptography.algorithms.PBKDF2
import dev.whyoleg.cryptography.algorithms.SHA1
import dev.whyoleg.cryptography.algorithms.SHA224
import dev.whyoleg.cryptography.algorithms.SHA256
import dev.whyoleg.cryptography.algorithms.SHA384
import dev.whyoleg.cryptography.algorithms.SHA3_224
import dev.whyoleg.cryptography.algorithms.SHA3_256
import dev.whyoleg.cryptography.algorithms.SHA3_384
import dev.whyoleg.cryptography.algorithms.SHA3_512
import dev.whyoleg.cryptography.algorithms.SHA512
import dev.whyoleg.cryptography.operations.SecretDerivation
import dev.whyoleg.cryptography.random.CryptographyRandom
import kotlinx.io.bytestring.encodeToByteString
import java.lang.IllegalStateException
import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import kotlin.io.encoding.Base64


/** Prefix identifying the hash format and algorithm */
private const val prefix = "PBKDF2WithHmacSHA512."

/**
 * Internal hash function using PBKDF2-HMAC-SHA512.
 *
 * Uses 100,000 iterations and produces a 512-bit (64-byte) output.
 * The high iteration count makes brute-force attacks computationally expensive.
 */
private suspend fun String.hash(salt: ByteArray): ByteArray =
    CryptographyProvider.Default
        .get(PBKDF2)
        .secretDerivation(
            SHA512,
            iterations = 100_000,
            outputSize = 512.bits,
            salt = salt
        )
    .deriveSecretToByteArray(this.encodeToByteString())

/**
 * Securely hashes a password using PBKDF2-HMAC-SHA512 with random salt.
 *
 * This function generates a cryptographically secure hash suitable for password storage.
 * Each call generates a unique random salt, so the same password will produce different hashes.
 *
 * **Performance Warning**: This is an intentionally slow operation (takes ~100-200ms)
 * and should only be called once during user registration or password changes.
 *
 * **Format**: The returned string has the format:
 * `PBKDF2WithHmacSHA512.<base64-salt>.<base64-hash>`
 *
 * @receiver The password/string to hash
 * @return A Base64-encoded hash string that can be stored in a database
 */
public suspend fun String.secureHash(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""

    val salt = CryptographyRandom.nextBytes(16)
    val secret = this.hash(salt)

    return prefix + Base64.encode(salt) + '.' + Base64.encode(secret)
}

/**
 * Verifies a password against a hash generated by [secureHash].
 *
 * This function re-hashes the password with the stored salt and performs
 * a constant-time comparison with the stored hash to prevent timing attacks.
 *
 * **Performance Warning**: This is an intentionally slow operation (takes ~100-200ms)
 * and should only be called once per authentication attempt.
 *
 * @receiver The password to check
 * @param hash The stored hash from [secureHash]
 * @return `true` if the password matches the hash, `false` otherwise
 */
public suspend fun String.checkAgainstHash(hash: String): Boolean {
    if (!hash.startsWith(prefix)) return false
    if (hash.isEmpty()) return false

    val data = hash.removePrefix(prefix)
    val salt = Base64.decode(data.substringBefore('.'))
    val secret = Base64.decode(data.substringAfter('.'))

    return this.hash(salt) contentEquals secret
}


/**
 * Java-based implementation of secure password hashing (for performance testing).
 *
 * This is an internal alternative implementation using javax.crypto that can be
 * compared against the Kotlin cryptography library for performance benchmarking.
 *
 * **Internal use only**: This function is used for testing and may be removed.
 *
 * **This is a very expensive operation and should only be called once**
 */
internal suspend fun String.secureHashJava(): String {
    if (this.startsWith(prefix)) return this
    if (this.isEmpty()) return ""
    val start = System.nanoTime()
    val salt = ByteArray(16)
    SecureRandom().nextBytes(salt)
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100_000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    return prefix + Base64.encode(salt) + "." + Base64.encode(key.encoded)
}

/**
 * Java-based implementation of password verification (for performance testing).
 *
 * This is an internal alternative implementation using javax.crypto that can be
 * compared against the Kotlin cryptography library for performance benchmarking.
 *
 * **Internal use only**: This function is used for testing and may be removed.
 *
 * **This is a very expensive operation and should only be called once**
 */
internal suspend fun String.checkAgainstHashJava(againstHash: String): Boolean {
    if (againstHash.isEmpty()) return false
    val against = againstHash.removePrefix(prefix)
    val start = System.nanoTime()
    val salt = Base64.decode(against.substringBefore('.'))
    val rest = against.substringAfter('.')
    val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")
    val spec = PBEKeySpec(this.toCharArray(), salt, 100_000, 512)
    val key = skf.generateSecret(spec)
    val tookNs = System.nanoTime() - start
    return Base64.encode(key.encoded) == rest
}

/*
 * TODO: API Recommendations
 *
 * 1. Add rate limiting guidance: Document that these functions should be protected by
 *    rate limiting in production to prevent denial-of-service attacks.
 *
 * 2. Consider blocking versions: Add secureHashBlocking() and checkAgainstHashBlocking()
 *    for consistency with the rest of the API.
 *
 * 3. Iteration count configuration: Consider making the iteration count configurable
 *    (with a secure default) to allow tuning based on performance requirements.
 *
 * 4. Consider Argon2: PBKDF2 is secure but Argon2id is the current best practice for
 *    password hashing. Consider adding Argon2id support if the cryptography library supports it.
 */
