// Package: com.lightningkite.lightningserver.files
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public func prepareUploadForNextRequestFields() -> Void {
    
    
    
}
public extension KeyPath where To == UploadForNextRequest {
    var _id: KeyPath<From, UUID> {
        get { return self.get(prop: UploadForNextRequest._idProp) }
    }
}
public extension KeyPath where To == UploadForNextRequest {
    var file: KeyPath<From, String> {
        get { return self.get(prop: UploadForNextRequest.fileProp) }
    }
}
public extension KeyPath where To == UploadForNextRequest {
    var expires: KeyPath<From, Date> {
        get { return self.get(prop: UploadForNextRequest.expiresProp) }
    }
}

