// Package: com.lightningkite.lightningserver.files
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public func prepareUploadForNextRequestFields() -> Void {
    
    
    
}
public extension PropChain where To == UploadForNextRequest {
    var _id: PropChain<From, UUID> {
        get { return self.get(prop: UploadForNextRequest._idProp) }
    }
}
public extension PropChain where To == UploadForNextRequest {
    var file: PropChain<From, String> {
        get { return self.get(prop: UploadForNextRequest.fileProp) }
    }
}
public extension PropChain where To == UploadForNextRequest {
    var expires: PropChain<From, Date> {
        get { return self.get(prop: UploadForNextRequest.expiresProp) }
    }
}

