// Package: com.lightningkite.lightningdb
// Generated by Khrysalis - this file will be overwritten.

//! Declares com.lightningkite.lightningdb.UUIDFor
export type UUIDFor<T> = string;
//! Declares com.lightningkite.lightningdb.UUIDFor
export let UUIDFor = String;

