// Package: com.lightningkite.ktordb
// Generated by Khrysalis - this file will be overwritten.
import { ObserveModelApi } from './ObserveModelApi'
import { ReadModelApi } from './ReadModelApi'
import { WriteModelApi } from './WriteModelApi'

//! Declares com.lightningkite.ktordb.CompleteModelApi
export abstract class CompleteModelApi<Model extends any> {
    protected constructor() {
    }
    
    public abstract readonly read: ReadModelApi<Model>;
    public abstract readonly write: WriteModelApi<Model>;
    public abstract readonly observe: ObserveModelApi<Model>;
}