// Package: com.lightningkite.lightningdb
// Generated by Khrysalis - this file will be overwritten.
import { Query } from './db/Query'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.lightningdb.ObserveModelApi
export abstract class ObserveModelApi<Model extends any> {
    protected constructor() {
    }
    
    public abstract observe(query: Query<Model>): Observable<Array<Model>>
}