// Package: com.lightningkite.ktordb.mock
// Generated by Khrysalis - this file will be overwritten.
import { Exception } from '@lightningkite/khrysalis-runtime'

//! Declares com.lightningkite.ktordb.mock.ItemNotFound
export class ItemNotFound extends Exception {
    public constructor(message: string) {
        super(message);
    }
}