// Package: com.lightningkite.lightningdb
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public class CompleteModelApi<Model : Codable & Hashable> {
    public init() {
        //Necessary properties should be initialized now
    }
    
    public var read: ReadModelApi<Model> { get { TODO() } }
    public var write: WriteModelApi<Model> { get { TODO() } }
    public var observe: ObserveModelApi<Model> { get { TODO() } }
}
