// Package: com.lightningkite.lightningdb
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

open class CompleteModelApi<Model : Codable & Hashable> {
    public init() {
        //Necessary properties should be initialized now
    }
    
    open var read: ReadModelApi<Model> { get { TODO() } }
    open var write: WriteModelApi<Model> { get { TODO() } }
    open var observe: ObserveModelApi<Model> { get { TODO() } }
}
