// Package: com.lightningkite.lightningdb
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public final class SignalData<Model : HasId> : CustomStringConvertible, Hashable {
    public var item: Model
    public var created: Bool
    public var deleted: Bool
    public init(item: Model, created: Bool, deleted: Bool) {
        self.item = item
        self.created = created
        self.deleted = deleted
        //Necessary properties should be initialized now
    }
    public func hash(into hasher: inout Hasher) {
        hasher.combine(item)
        hasher.combine(created)
        hasher.combine(deleted)
        
    }
    public static func == (lhs: SignalData, rhs: SignalData) -> Bool { return lhs.item == rhs.item && lhs.created == rhs.created && lhs.deleted == rhs.deleted }
    public var description: String { return "SignalData(item=\(String(kotlin: self.item)), created=\(String(kotlin: self.created)), deleted=\(String(kotlin: self.deleted)))" }
    public func copy(item: Model? = nil, created: Bool? = nil, deleted: Bool? = nil) -> SignalData<Model> { return SignalData(item: item ?? self.item, created: created ?? self.created, deleted: deleted ?? self.deleted) }
}
